### ISSUE TITLE
Lotus Notes: Test modifying all events in the future (RANGE=THISANDFUTURE)

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python-recurring-ical-events#184]
If you are using Lotus Notes, please provide us with example files where you modify all future events. This way, we can test compatibility.

## Context

In #75, we solved editing event series from a certain date on: you can now successfully change fields like SUMMARY or DESCRIPTION, change the length of the event and all subsequent ones and also move the event. However, this should be validated with a specific application. Several sources claim that Lotus Notes makes use of this part of RFC5545.

## TODO

- upload the example here with a screenshot of what it looks like:
    - [ ] modify all events in the future and 
    - [ ] move an event and subsequent ones
- [ ] create and import an event with RDATE of type PERIOD (will be generated) to test what is understood there.
